-- ============================================================================
-- $Id: sip10-ddl.sql 19 2010-05-02 05:16:10Z  $
-- 
-- Copyright (c) 2010 Manning Publications Co.
-- 
-- Willie Wheeler (willie.wheeler@gmail.com)
-- 
-- Book web site   - http://www.manning.com/wheeler/
-- Book blog       - http://springinpractice.com/
-- Author web site - http://wheelersoftware.com/
-- ============================================================================

create table contact (
    id bigint generated by default as identity (start with 1, increment by 1) not null primary key,
    last_name varchar(40) not null,
    first_name varchar(40) not null,
    mi char(1),
    email varchar(80),
	date_created timestamp default 0,
	date_modified timestamp default current_timestamp,
	unique (last_name, first_name, mi)
);
